### ISSUE TITLE
Google search

### ISSUE THREAD

**Issue by miki995** [egek92/SearchOverflow-IntelliJ#2]
Hello,

You can consider to implement this as google search.

Why: 
* Stackoverflow is not giving results on some queries, and you know people, they see nothing and they delete your plugin, so I suppose you'll look at problem and make it like I proposed.

Looking forward to hear answer from you.

Best, Miroslav Maksimovic

**Comment by egkz** [comment]
All Jetbrains IDE's has Search on Google section by default, I'm planning to implement more complicated search queries in future, see https://github.com/egek92/SearchOverflow-IntelliJ#contributing

**Comment by miki995** [comment]
Oh, I didn't realized it yet, thanks for letting me know.
